/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Market_ui;

import Business.Business;
import Business.Market.Market;
import Business.Market.MarketOffer;
import Business.Product.Product;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Utility.Validations;

/**
 *
 * @author prashantreddy
 */
public class CreateMarketOffer extends javax.swing.JPanel {

    /**
     * Creates new form MarketOffer
     */
    private JPanel userProcessContainer;
    private Business business;
    public CreateMarketOffer(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business= business;
        this.userProcessContainer= userProcessContainer;
        for(Market market : business.getMarketList().getMarketList()) {
             
//       .addItem(string);
            marketComboBox.addItem(market);
        }
         for(Supplier supplier : business.getSupplierDirectory().getSupplierList()) {
             
//       .addItem(string);
            supplierComboBox.addItem(supplier);
        }
         populateProductCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        marketComboBox = new javax.swing.JComboBox();
        supplierComboBox = new javax.swing.JComboBox();
        productComboBox = new javax.swing.JComboBox();
        flrTxt = new javax.swing.JTextField();
        tarTxt = new javax.swing.JTextField();
        ceilTxt = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Offer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 55, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Market Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 104, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Supplier Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 149, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 193, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Floor Price:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 234, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Target Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 278, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ceil Price:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 327, -1, -1));

        marketComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketComboBoxActionPerformed(evt);
            }
        });
        add(marketComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 100, 121, -1));

        supplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboBoxActionPerformed(evt);
            }
        });
        add(supplierComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 145, 121, -1));

        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 189, 121, -1));

        flrTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                flrTxtKeyPressed(evt);
            }
        });
        add(flrTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 234, 121, -1));

        tarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarTxtActionPerformed(evt);
            }
        });
        tarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tarTxtKeyPressed(evt);
            }
        });
        add(tarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 278, 121, -1));

        ceilTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ceilTxtKeyPressed(evt);
            }
        });
        add(ceilTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 322, 121, -1));

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 376, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
   public void populateProductCombo()
   {
       productComboBox.removeAllItems();
       Supplier supplier= (Supplier)supplierComboBox.getSelectedItem();
       for (Product product : supplier.getProductCatalog().getProductList()) {
           productComboBox.addItem(product);
       }
   }
    private void marketComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marketComboBoxActionPerformed

    private void tarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarTxtActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        MarketOffer marketOffer = business.getMarketOfferCatalog().addMarketOffer();
        Product product = (Product)productComboBox.getSelectedItem();
        Market market = (Market)marketComboBox.getSelectedItem();
        marketOffer.setFloorRatio(Double.parseDouble(flrTxt.getText()));
        marketOffer.setTargetRatio(Double.parseDouble(tarTxt.getText()));
        marketOffer.setCeilRatio(Double.parseDouble(ceilTxt.getText()));
        marketOffer.setProduct(product);
        marketOffer.setMarket(market);
        JOptionPane.showMessageDialog(null,"Created succesfully");
    }//GEN-LAST:event_createBtnActionPerformed

    private void supplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboBoxActionPerformed
        // TODO add your handling code here:
        productComboBox.removeAllItems();
        populateProductCombo();
    }//GEN-LAST:event_supplierComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer); 
        
        Component[] componentArray=userProcessContainer.getComponents();
        ManageMarketOffer manageOffer = (ManageMarketOffer)userProcessContainer.getComponent(componentArray.length -1);
        manageOffer.populateTable();
    }//GEN-LAST:event_backBtnActionPerformed

    private void flrTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_flrTxtKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_flrTxtKeyPressed

    private void tarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tarTxtKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tarTxtKeyPressed

    private void ceilTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ceilTxtKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ceilTxtKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField ceilTxt;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField flrTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox marketComboBox;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JComboBox supplierComboBox;
    private javax.swing.JTextField tarTxt;
    // End of variables declaration//GEN-END:variables
}
