/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Market_ui;

import Business.Business;
import Business.Market.Market;
import Business.Market.MarketOffer;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prashantreddy
 */
public class ManageMarketOffer extends javax.swing.JPanel {

    /**
     * Creates new form ManageMarketOffer
     */
     private JPanel userProcessContainer;
    private Business business;
    public ManageMarketOffer(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business= business;
        this.userProcessContainer= userProcessContainer;
        ComboBox.removeAllItems();
        for (Market market : business.getMarketList().getMarketList()) {
            ComboBox.addItem(market);
            
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketOfferTable = new javax.swing.JTable();
        ComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setText("Create Market Offer >>");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 536, 202, 51));

        updateBtn.setText("Update Market Offer >>");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 536, -1, 51));

        marketOfferTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market Name", "Market Offer Id", "Product Name", "Floor Ratio", "Target Ratio", "Ceil Ratio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(marketOfferTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 98, 641, -1));

        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 59, 180, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Market ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 63, 62, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Market Offer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 19, -1, -1));

        jButton1.setText("Delete Market");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 536, 180, 51));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
public void populateTable()
{
   Market market= (Market) ComboBox.getSelectedItem();
   DefaultTableModel dtm = (DefaultTableModel)marketOfferTable.getModel();
        dtm.setRowCount(0);
        for (MarketOffer marketOffer : business.getMarketOfferCatalog().getMarketOfferList()) {
            if(market.equals(marketOffer.getMarket()))
            {
                       
                    Object row[] = new Object[6];
                    row[0] = market;
                    row[1] = marketOffer;
                    row[2]= marketOffer.getProduct().getProductName();
                    row[3]= marketOffer.getFloorRatio();
                    row[4]= marketOffer.getTargetRatio();
                    row[5]= marketOffer.getCeilRatio();
 
                    dtm.addRow(row);  
            }
        
    }

           
}
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
                CreateMarketOffer marketOffer= new CreateMarketOffer(userProcessContainer, business);
        userProcessContainer.add("CreateMarketOffer", marketOffer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow=marketOfferTable.getSelectedRow();
        if(selectedrow>=0)
        {
         MarketOffer marketOffer=(MarketOffer)marketOfferTable.getValueAt(selectedrow,1);
        UpdateMarketOffer updateMarketOffer= new UpdateMarketOffer(userProcessContainer, business, marketOffer);
        userProcessContainer.add("UpdateMarketOffer", updateMarketOffer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a row first");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
        
        populateTable();
        
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
                       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                int selectedrow=marketOfferTable.getSelectedRow();
   if(selectedrow>=0)
        {    
            JOptionPane.showMessageDialog(null,"Are you sure you want to delete this entry?");
            MarketOffer marketOffer=(MarketOffer)marketOfferTable.getValueAt(selectedrow,0);
            business.getMarketOfferCatalog().deleteMarketOffer(marketOffer);
            populateTable();
             JOptionPane.showMessageDialog(null,"Person deleted");
        }
       else
            JOptionPane.showMessageDialog(null,"Please select a row first");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable marketOfferTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
