/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Market_ui;

import Supplier_ui.*;
import Person_ui.*;
import Business.Business;
import Business.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Supplier.*;
import Business.Market.*;
/**
 *
 * @author raj
 */
public class MarketJPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanelForm
     */
    private JPanel userProcessContainer;
    private Business business;
    public MarketJPanelForm(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        populateMarketTable();
    }
    
    public void populateMarketTable(){
        DefaultTableModel dtm = (DefaultTableModel)marketTable.getModel();
        dtm.setRowCount(0);
        
        for (Market mar:business.getMarketList().getMarketList()){ 
                    Object row[] = new Object[4];
                    row[0] = mar;
                    row[1] = mar.getMarketId();
                    
                    
                    
                    dtm.addRow(row);  
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addSupplierButton = new javax.swing.JButton();
        updateSupplier = new javax.swing.JButton();
        deleteSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Market");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 330, 61));

        addSupplierButton.setText("Add Market");
        addSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addSupplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 130, 50));

        updateSupplier.setText("Update Market");
        updateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(updateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 150, 40));

        deleteSupplier.setText("Delete Market");
        deleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(deleteSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 140, 40));

        marketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market Name", "Market Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(marketTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 85, 505, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        int selectedrow=marketTable.getSelectedRow();
        
        if(selectedrow>=0)
        {  
        Market res=(Market)marketTable.getValueAt(selectedrow,0);
        UpdateMarket up= new UpdateMarket(userProcessContainer,business,res);
        userProcessContainer.add("UpdateMarket", up);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(updateSupplier,"Please select a row first");
    }//GEN-LAST:event_updateSupplierActionPerformed

    private void addSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierButtonActionPerformed
        CreateMarket cp= new CreateMarket(userProcessContainer, business);
        userProcessContainer.add("CreateMarket", cp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addSupplierButtonActionPerformed

    private void deleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierActionPerformed
       int selectedrow= marketTable.getSelectedRow();
       if(selectedrow>=0)
        {    
            JOptionPane.showMessageDialog(deleteSupplier,"Are you sure you want to delete this entry?");
            Market res=(Market)marketTable.getValueAt(selectedrow,0);
            business.getMarketList().deleteMarket(res);
            populateMarketTable();
            JOptionPane.showMessageDialog(deleteSupplier,"Person deleted");
        }
       else
            JOptionPane.showMessageDialog(updateSupplier,"Please select a row first");
    }//GEN-LAST:event_deleteSupplierActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
               userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplierButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable marketTable;
    private javax.swing.JButton updateSupplier;
    // End of variables declaration//GEN-END:variables
}
