/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Business;
import Business.Person.Person;
import Customer_ui.CustomerJPanelForm;
import Market_ui.*;
import Person_ui.*;
import Supplier_ui.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author raj
 */

public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Person person;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,Business business, Person person) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        managePerson = new javax.swing.JButton();
        manageSupplier = new javax.swing.JButton();
        manageMarket = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageOfferBtn = new javax.swing.JButton();
        perBtn = new javax.swing.JButton();
        totalOrderList = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome System Admin");

        managePerson.setText("Manage Person");
        managePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonActionPerformed(evt);
            }
        });

        manageSupplier.setText("Manage Supplier");
        manageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierActionPerformed(evt);
            }
        });

        manageMarket.setText("Manage Market");
        manageMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMarketActionPerformed(evt);
            }
        });

        jButton1.setText("Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageOfferBtn.setText("Manage Market Offer");
        manageOfferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOfferBtnActionPerformed(evt);
            }
        });

        perBtn.setText("Performance Monitor");
        perBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perBtnActionPerformed(evt);
            }
        });

        totalOrderList.setText("Total Order List");
        totalOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalOrderListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(manageMarket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageOfferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(perBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(managePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(manageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageOfferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void managePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonActionPerformed
       PersonJPanelForm pjp= new PersonJPanelForm(userProcessContainer, business);
       userProcessContainer.add("PersonJPanelForm", pjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonActionPerformed

    private void manageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierActionPerformed
       SupplierJPanelForm spjp= new SupplierJPanelForm(userProcessContainer, business);
       userProcessContainer.add("SupplierJPanelForm", spjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSupplierActionPerformed

    private void manageMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMarketActionPerformed
        MarketJPanelForm mjp= new MarketJPanelForm(userProcessContainer, business);
        userProcessContainer.add("MarketJPanelForm", mjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMarketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustomerJPanelForm cjp= new CustomerJPanelForm(userProcessContainer, business);
        userProcessContainer.add("CustomerJPanelForm", cjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageOfferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOfferBtnActionPerformed
        // TODO add your handling code here:
               ManageMarketOffer marketOffer= new ManageMarketOffer(userProcessContainer, business);
        userProcessContainer.add("ManageMarketOffer", marketOffer);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOfferBtnActionPerformed

    private void perBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perBtnActionPerformed
        // TODO add your handling code here:
        ViewSalesWorkAreaJPanel monitor= new ViewSalesWorkAreaJPanel(userProcessContainer, business, person);
        userProcessContainer.add("ViewSalesWorkAreaJPanel", monitor);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_perBtnActionPerformed

    private void totalOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalOrderListActionPerformed
        TotalOrderListJPanel toljp= new TotalOrderListJPanel(userProcessContainer, business, person);
        userProcessContainer.add("TotalOrderListJPanel",toljp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_totalOrderListActionPerformed

                           



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageMarket;
    private javax.swing.JButton manageOfferBtn;
    private javax.swing.JButton managePerson;
    private javax.swing.JButton manageSupplier;
    private javax.swing.JButton perBtn;
    private javax.swing.JButton totalOrderList;
    // End of variables declaration//GEN-END:variables
}
