/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Business;
import Business.Person.Person;
import Customer_ui.CustomerJPanelForm;
import Market_ui.*;
import Person_ui.*;
import Supplier_ui.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author raj
 */

public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Person person;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,Business business, Person person) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        managePerson = new javax.swing.JButton();
        manageSupplier = new javax.swing.JButton();
        manageMarket = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageOfferBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome System Admin");
        jPanel1.add(jLabel1);

        managePerson.setText("Manage Person");
        managePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonActionPerformed(evt);
            }
        });
        jPanel1.add(managePerson);

        manageSupplier.setText("Manage Supplier");
        manageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(manageSupplier);

        manageMarket.setText("Manage Market");
        manageMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMarketActionPerformed(evt);
            }
        });
        jPanel1.add(manageMarket);

        jButton1.setText("Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        manageOfferBtn.setText("Manage Market Offer");
        manageOfferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOfferBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageOfferBtn);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void managePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonActionPerformed
       PersonJPanelForm pjp= new PersonJPanelForm(userProcessContainer, business);
       userProcessContainer.add("ManageSupplierAdministrative", pjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonActionPerformed

    private void manageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierActionPerformed
       SupplierJPanelForm spjp= new SupplierJPanelForm(userProcessContainer, business);
       userProcessContainer.add("ManageSupplierAdministrative", spjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSupplierActionPerformed

    private void manageMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMarketActionPerformed
        MarketJPanelForm mjp= new MarketJPanelForm(userProcessContainer, business);
        userProcessContainer.add("ManageSupplierAdministrative", mjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMarketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustomerJPanelForm mjp= new CustomerJPanelForm(userProcessContainer, business);
        userProcessContainer.add("ManageSupplierAdministrative", mjp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageOfferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOfferBtnActionPerformed
        // TODO add your handling code here:
               ManageMarketOffer marketOffer= new ManageMarketOffer(userProcessContainer, business);
        userProcessContainer.add("ManageSupplierAdministrative", marketOffer);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOfferBtnActionPerformed

                           



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageMarket;
    private javax.swing.JButton manageOfferBtn;
    private javax.swing.JButton managePerson;
    private javax.swing.JButton manageSupplier;
    // End of variables declaration//GEN-END:variables
}
